# Generated by Django 4.1.2 on 2022-11-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupperm',
            name='permission_level',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Organizer'), (2, 'Admin')], default=0, help_text='Determines what capabilites user will have'),
        ),
    ]
