# Generated by Django 4.1.2 on 2022-11-05 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_alter_groupperm_permission_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('group_role', models.CharField(blank=True, max_length=50, null=True)),
                ('permission_level', models.IntegerField(choices=[(0, 'User'), (1, 'Organizer'), (2, 'Admin')], default=0, help_text='Determines what capabilites user will have')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'member')},
            },
        ),
        migrations.DeleteModel(
            name='GroupPerm',
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, through='group.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
