# Generated by Django 4.1.2 on 2022-12-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='group.groupmembership'),
        ),
    ]
