# Generated by Django 4.1.2 on 2022-12-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_topics_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.groupmembership'),
        ),
    ]
