# Generated by Django 4.1.2 on 2022-12-16 19:07

from django.db import migrations, models
import django.db.models.deletion
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_topic_delete_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(default=group.models.InviteCode.createID, max_length=8, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, default=group.models.InviteCode.create_expiration_date, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
    ]
