# Generated by Django 4.1.2 on 2022-12-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_invitecode'),
    ]

    operations = [
    ]
