# Generated by Django 4.1.2 on 2022-12-16 19:15

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20221216_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='invite_code',
            field=models.CharField(default=group.models.InviteCode.createID, editable=False, max_length=8, unique=True),
        ),
    ]
