# Generated by Django 4.1.2 on 2022-12-16 19:16

from django.db import migrations, models
import group.models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_alter_invitecode_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecode',
            name='expiration_date',
            field=models.DateTimeField(default=group.models.InviteCode.create_expiration_date, editable=False),
        ),
    ]
