# Generated by Django 4.1.2 on 2022-12-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0011_alter_invitecode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_title',
            field=models.CharField(max_length=50),
        ),
    ]
