# Generated by Django 4.1.2 on 2022-10-29 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('event_name', models.CharField(help_text='Enter Event Name', max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topics', models.TextField(help_text='Enter Topics for Meeting')),
                ('status', models.CharField(choices=[('s', 'Scheduled'), ('p', 'Postponed'), ('c', 'Cancelled'), ('m', 'Maintenance')], default='s', help_text='Status of Event', max_length=1)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='schedule.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.TextField(default='test group')),
                ('all_day', models.BooleanField()),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('p', 'Pending'), ('d', 'Denied'), ('a', 'Approved')], max_length=1)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
