# Generated by Django 4.1.2 on 2022-11-01 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedule', '0002_event_group_alter_event_artists_delete_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
