# Generated by Django 4.1.2 on 2022-11-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_rename_artists_event_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Denied'), (2, 'Approved')], default=0),
        ),
    ]
