# Generated by Django 4.1.2 on 2022-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Scheduled'), (1, 'Postponed'), (2, 'Cancelled'), (3, 'Maintenance')], default=0, help_text='Status of Event'),
        ),
    ]
