# Generated by Django 4.1.2 on 2022-11-08 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupmembership_delete_groupperm_alter_group_members'),
        ('schedule', '0007_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
    ]
