# Generated by Django 4.1.2 on 2022-11-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_groupmembership_delete_groupperm_alter_group_members'),
        ('schedule', '0008_alter_conflict_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer', to='group.groupmembership'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(to='group.groupmembership'),
        ),
    ]
