# Generated by Django 4.1.2 on 2022-11-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_remove_event_date_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='staff',
        ),
    ]
