# Generated by Django 4.1.2 on 2022-11-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_rename_event_name_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
