# Generated by Django 4.1.2 on 2022-11-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_event_allday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='allday',
        ),
    ]
