# Generated by Django 4.1.2 on 2022-12-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_topic_delete_topics'),
        ('schedule', '0014_remove_event_allday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='group.topic'),
        ),
    ]
