# Generated by Django 4.1.2 on 2022-12-07 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_event_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='topics',
            new_name='_topic',
        ),
    ]
