# Generated by Django 4.1.2 on 2022-12-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_topic_delete_topics'),
        ('schedule', '0018_rename_end_date_conflict_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflict',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.groupmembership'),
        ),
    ]
