# Generated by Django 4.1.2 on 2022-12-10 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_alter_conflict_requested_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conflict',
            name='group',
        ),
    ]
